# Generated by Django 5.1.2 on 2024-12-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='queue_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
